#!/usr/bin/env bash
#
# Publish the built site to the gh-pages branch.
#
# The branch holds the contents of dist/ and nothing else: no source, and no
# history of its own worth keeping. One commit is replaced each time, which is
# why it is an orphan branch and why the push is forced. Nothing on it is
# authored, so nothing on it is worth a merge.
#
# Two reasons the build cannot happen on GitHub's side instead. The textures
# are generated by scripts/build_globe_textures.py and downloaded by
# scripts/fetch_earth_imagery.py, and both are gitignored outputs; and the
# Earth beat is rendered by a headless browser driving a running dev server.
# Building here and publishing the result is the honest version of that.
#
#   ./scripts/deploy.sh
#
set -euo pipefail
cd "$(dirname "$0")/.."

WORKTREE="${TMPDIR:-/tmp}/vestigo-gh-pages"

npm run build

git worktree remove --force "$WORKTREE" 2>/dev/null || true
# --orphan the first time, because there is no branch yet and nothing sensible
# for it to descend from; after that, check out what is already there.
if git show-ref --quiet refs/heads/gh-pages; then
  git worktree add --force "$WORKTREE" gh-pages
else
  git worktree add --orphan -b gh-pages "$WORKTREE"
fi

# --delete, so a file dropped from the build is dropped from the branch too.
# Without it the branch accumulates every asset the site has ever carried,
# which is how a 16 MB deploy quietly becomes a 200 MB one.
rsync -a --delete --exclude .git dist/ "$WORKTREE/"

cd "$WORKTREE"
git add -A
# Nothing to say that the diff does not, and the branch is not a record of
# anything. The date is the only part worth writing down.
git commit -q -m "Build $(date -u '+%Y-%m-%d %H:%M UTC')" || {
  echo "nothing changed"
  exit 0
}
# Everything above is local. DRY=1 stops here, so what is about to be
# published can be looked at before it is.
if [ "${DRY:-}" = "1" ]; then
  echo "dry run. built and committed to gh-pages, not pushed:"
  echo "  $WORKTREE"
  exit 0
fi

git push -f origin gh-pages
echo "pushed -> https://vestigo.earth/"
