#!/usr/bin/env bash
#
# Publish the built site to the gh-pages branch.
#
# The branch holds the contents of dist/ and nothing else: no source, and no
# history of its own worth keeping. One commit is replaced each time, which is
# why it is an orphan branch and why the push is forced. Nothing on it is
# authored, so nothing on it is worth a merge.
#
# Two reasons the build cannot happen on GitHub's side instead. The textures
# are generated by scripts/build_globe_textures.py and downloaded by
# scripts/fetch_earth_imagery.py, and both are gitignored outputs; and the
# Earth beat is rendered by a headless browser driving a running dev server.
# Building here and publishing the result is the honest version of that.
#
#   ./scripts/deploy.sh
#
set -euo pipefail
cd "$(dirname "$0")/.."

WORKTREE="${TMPDIR:-/tmp}/vestigo-gh-pages"

# Cleaned first. Vite hashes asset filenames and does not remove the old ones,
# so dist/ accumulates every build it has ever done. That is normally harmless
# and once was not: a deploy went out with an index.html from one build and
# assets from another, and the live site came up as unstyled HTML with a plain
# underlined VESTIGO on white.
rm -rf dist
npm run build

git worktree remove --force "$WORKTREE" 2>/dev/null || true
# --orphan the first time, because there is no branch yet and nothing sensible
# for it to descend from; after that, check out what is already there.
if git show-ref --quiet refs/heads/gh-pages; then
  git worktree add --force "$WORKTREE" gh-pages
else
  git worktree add --orphan -b gh-pages "$WORKTREE"
fi

# -c, and this is not paranoia.
#
# rsync decides whether to copy by comparing size and modification time. Vite
# rewrites index.html by swapping one ten-character content hash for another,
# which does not change its length: the old file and the new one are both
# exactly 9231 bytes. Given a checked-out mtime that matches, rsync concludes
# they are the same file and skips it — so the assets update, the HTML that
# names them does not, and the deploy ships an index.html pointing at files
# that were deleted in the same breath.
#
# That is the failure that took the site down: a white page with an underlined
# heading. The one file whose contents matter most is the one whose size can
# never change, because a hash swap is length-preserving. Compare contents.
#
# --delete, so a file dropped from the build is dropped from the branch too.
# Without it the branch accumulates every asset the site has ever carried,
# which is how a 16 MB deploy quietly becomes a 200 MB one.
rsync -ac --delete --exclude .git dist/ "$WORKTREE/"

cd "$WORKTREE"

# ---------------------------------------------------------------------------
# Refuse to publish a set that does not agree with itself.
#
# index.html names its script and stylesheet by content hash. If either is
# missing from what is about to be pushed, the page loads and renders nothing —
# no error in the console anyone will see, no failed request anyone is
# watching, just a white page with an underlined heading on it. That shipped
# once. It cannot be allowed to ship silently again, so this turns it from a
# broken deploy into a failed one.
# ---------------------------------------------------------------------------
missing=""
for ref in $(grep -oE '/assets/[^"]+' index.html | sort -u); do
  [ -f ".${ref}" ] || missing="${missing} ${ref}"
done
if [ -n "$missing" ]; then
  echo "refusing to publish: index.html references files that are not here:" >&2
  for m in $missing; do echo "  $m" >&2; done
  echo "what is here:" >&2
  ls assets/ >&2
  exit 1
fi
echo "  index.html and assets agree"

git add -A
# Nothing to say that the diff does not, and the branch is not a record of
# anything. The date is the only part worth writing down.
git commit -q -m "Build $(date -u '+%Y-%m-%d %H:%M UTC')" || {
  echo "nothing changed"
  exit 0
}
# Everything above is local. DRY=1 stops here, so what is about to be
# published can be looked at before it is.
if [ "${DRY:-}" = "1" ]; then
  echo "dry run. built and committed to gh-pages, not pushed:"
  echo "  $WORKTREE"
  exit 0
fi

git push -f origin gh-pages
echo "pushed -> https://vestigo.earth/"
